api_version = "2026-07"

[[extensions]]
name = "order-support"
handle = "order-support"
type = "ui_extension"
uid = "407d2d16-b4c7-8315-0ece-baad4f9723925adfcf78"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.thank-you.block.render"
